In [28]:
import pandas as pd
import numpy as np
from sklearn import tree
data = pd.read_csv('train.csv')
data_test = pd.read_csv('test.csv')
data_y = pd.read_csv('sample_submission.csv')
x_test

        Elevation  Aspect
0            2680     354
1            2683       0
2            2713      16
3            2709      24
4            2706      29
5            2699      21
6            2699      15
7            2696      10
8            2696      17
9            2693      14
10           2693      24
11           2686       7
12           2690       6
13           2686      57
14           2680      76
15           2670      93
16           2722       5
17           2722     358
18           2722       0
19           2722       7
20           2719      14
21           2716      23
22           2709      19
23           2709      17
24           2703      16
25           2703      11
26           2699      18
27           2699      17
28           2696      39
29           2690      36
...           ...     ...
565862       2431     182
565863       2436     219
565864       2441     201
565865       2442     191
565866       2444     202
565867       2450     203
565868       2455     189
565869       2455     181
565870       2455     166
565871       2445     157
565872       2441     173
565873       2440     173
565874       2437     170
565875       2437     174
565876       2435     171
565877       2433     168
565878       2429     166
565879       2426     168
565880       2423     169
565881       2421     172
565882       2419     168
565883       2415     161
565884       2410     158
565885       2405     159
565886       2401     157
565887       2396     153
565888       2391     152
565889       2386     159
565890       2384     170
565891       2383     165

[565892 rows x 2 columns]

In [23]:
x = data[['Elevation', 'Aspect']]
y = data[['Cover_Type']]
x_test = data_test[['Elevation', 'Aspect']]
y_test = data_y[['Cover_Type']]

In [6]:
model = tree.DecisionTreeClassifier(criterion = 'gini')

In [7]:
model.fit(x , y)
model.score(x , y)

0.991468253968254

In [26]:
predicted = model.predict(x_test)
predicted
sum = 0
for i in range (0 , 565892):
    if predicted[i] == 1:
        sum = sum + 1

In [17]:
model.score(x_test, y_test)

0.31576873325652244

In [31]:
sum / 565891

0.3157692912592708